### ISSUE TITLE
Adding Autosave feature after a successful combat

### ISSUE THREAD

**Issue by Tokelin** [justindujardin/angular-rpg#26]
I am interested in giving a go at adding the functionality myself. What do you think the complexity of the task would be? I have only recently discovered this project and am still quite lost (mainly just playing it, it's a pretty good game!).

My current understanding is that it shouldn't be too hard to add the feature - saving is already there, just trigger it after a combat ends.

Further improvement could be adding some kind of settings checkbox to turn it on or off. I know some people wouldn't like the feature.

**Comment by justindujardin** [comment]
Thanks for opening a PR to support this issue. I'm glad you figured out how to update the save files after combat is over. I think we need to add a checkbox to toggle this feature on/off before I can accept it. 

A big part of how I develop things for this is to load a save state and then do some stuff, then refresh to get back to the old state. So, this change would cause problems if I was testing something that required me to go through a few combats to verify it.

I think you could explore adding the checkbox by putting on next to the save/load buttons in the `src/app/components/party-menu-component.html`. You could have the checkbox write a value to [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and then read that value before saving when combat completes.

**Comment by justindujardin** [comment]
Closed by #27
