### ISSUE TITLE
Ship position resets after encounters

### ISSUE THREAD

**Issue by urish** [justindujardin/angular-rpg#6]
# I'm submitting a...
[x] bug report
[ ] feature request

Ship should stay in the same place after an encounter. However, if you are sailing and have an encounter while in the sea, the ship position will reset after the encounter, and you will be left stuck in the middle of the sea.

**Comment by justindujardin** [comment]
Yeah, the sailing code didn't survive the last Framework change it looks like. I opened up a PR that mostly fixes it up: https://github.com/justindujardin/angular-rpg/pull/7

**Comment by urish** [comment]
Yay!

**Comment by urish** [comment]
Thank you :)
